# Aderyn Configuration File
# This is a sample configuration for Aderyn

# The root directory of smart contracts
# root = "."

# By default, aderyn will try to extract the following values based on the framework that is being used.
# However, if you want to be explicit consider mentioning them.

# The source directory containing the Solidity contracts.
# This is often "contracts/" or "src/"
# src = "src/"

# Contract files to include in the analysis.
# This is a list of strings representing the file paths of the contracts to include.
# It can be a partial match like "/interfaces/", which will include all files with "/interfaces/" in the file path.
# Or it can be a full match like "Counter.sol", which will include only the file with the exact file.
# If not specified, all contract files in the source directory will be included.
# Example:
# include = ["Counter.sol"]
# include = []

# Contract files to exclude from the analysis.
# This is a list of strings representing the file paths of the contracts to exclude.
# It can be a partial match like "/interfaces/", which will exclude all files with "/interfaces/" in the file path.
# Or it can be a full match like "Counter.sol", which will exclude only the file with the exact file.
# If not specified, no contract files will be excluded.
# Example:
# exclude = ["/interfaces/"]
# exclude = []

## Remappings used for compiling the contracts.
# Example:
# remappings = ["@oz/contracts=lib/openzeppelin-contracts/contracts"]
