#!/usr/bin/env bash
set -e

# TODO: Adjust this after merge 
DYNAMIC_SCRIPT_URL="https://raw.githubusercontent.com/Cyfrin/aderyn/master/cyfrinup/dynamic_script"

# Keep it minimal
main() {
  need_cmd curl
  ensure curl -L "$DYNAMIC_SCRIPT_URL" | bash
}

need_cmd() {
  if ! check_cmd "$1"; then
    err "need '$1' (command not found)"
  fi
}

check_cmd() {
  command -v "$1" > /dev/null 2>&1
}

# Run a command that should never fail. If the command fails execution
# will immediately terminate with an error showing the failing
# command.
ensure() {
  if ! "$@"; then err "command failed: $*"; fi
}

# --- Adding a banner --- 
banner() {
    printf "
                     
⠀⠀⠀⡠⠔⠂⠁⠀⠀⠀⠀⠀⠈⠐⡂⠀⠀     █████╗  ██████╗  ███████╗ ██████╗  ██╗   ██╗ ███╗   ██╗                 
⠀⡠⠀⠀⠀⠀⠀⡀⠀⠀⠀⠀⠀⠀⢈⣀⡀    ██╔══██╗ ██╔══██╗ ██╔════╝ ██╔══██╗ ╚██╗ ██╔╝ ████╗  ██║ 
⠰⠀⠀⠀⢠⢆⣤⣆⠀⠀⠤⠤⠄⢀⡀⠑⠀    ███████║ ██║  ██║ █████╗   ██████╔╝  ╚████╔╝  ██╔██╗ ██║
⡌⠊⠒⠠⡁⠈⠛⠋⡠⠊⠀⠠⠀⠀⠀⠀⠉    ██╔══██║ ██║  ██║ ██╔══╝   ██╔══██╗   ╚██╔╝   ██║╚██╗██║  
⡅⠀⢀⣰⣧⠁⠀⠉⠀⠀⢀⠂⠀⠀⠀⠀⣠    ██║  ██║ ██████╔╝ ███████╗ ██║  ██║    ██║    ██║ ╚████║ 
⠇⣬⣿⣿⣿⠀⠀⠀⠀⠠⠂⠀⠀⠀⢄⣴⣿    ╚═╝  ╚═╝ ╚═════╝  ╚══════╝ ╚═╝  ╚═╝    ╚═╝    ╚═╝  ╚═══╝
⠈⠻⣗⡀⢡⢁⠀⢀⠔⠁⠀⠀⠀⢠⣿⣿⣿      
⠀⠀⠀⠁⠈⡀⠒⠃⠀⠀⠀⠀⠀⠸⣿⣿⡿        A powerful Solidity static analyzer that takes a  
⠀⠀⠀⠀⠀⠁⠀⠀⡀⠀⠀⠀⠀⡄⢸⠚⠃          bird's eye view over your smart contracts.
⠀⠀⠀⠀⠀⠇⠀⢠⠁⠀⡀⠀⢠⠀⡚⠀⠀
⠀⠀⠀⠀⠘⠀⠂⠀⡀⠔⡅⡠⠂⠉              Official Docs - https://docs.cyfrin.io/   
                                         
                                        ᴘᴏᴡᴇʀᴇᴅ ʙʏ ᴄʏꜰʀɪɴ
    
    "
}

# Calling banner function 
banner 

main "$@" || exit 1