# Runs `cargo update` periodically.

name: Dependencies

on:
  schedule:
    # Run weekly
    - cron: "0 13 * * SUN"
  workflow_dispatch:
    # Needed so we can run it manually

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    uses: cyfrin/ci/.github/workflows/cargo-update-pr.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
