# Runs `cargo update` periodically.
# Reference:
# https://github.com/paradigmxyz/solar/blob/main/.github/workflows/dependencies.yml

name: Dependencies

on:
  schedule:
    # Run weekly
    - cron: "0 0 * * SUN"
  workflow_dispatch:
    # Needed so we can run it manually

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    uses: ithacaxyz/ci/.github/workflows/cargo-update-pr.yml@dev
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
